#!/bin/bash

# Custom clean script
# It calls biicode clean command and reconfigures the project.
# Note that means the netbeans project, which depends on the cmake data generated by biicode,
# is deleted (Its located on ./cmake). So this scripts saves the project prior to clean and
# restores it after reconfiguring the biicode project.

mkdir ./tmp_netbeans
cp -r ./cmake/nbproject ./tmp_netbeans

bii clean
bii cpp:configure
bii find

cp -r ./tmp_netbeans/nbproject ./cmake
rm -r -f ./tmp_netbeans
